//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VignaharaServices.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vignahara_Contact
    {
        public int ContactID { get; set; }
        public int PortalID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string Telephone01 { get; set; }
        public string Telephone02 { get; set; }
        public string Telephone03 { get; set; }
        public string TelephoneType01 { get; set; }
        public string TelephoneType02 { get; set; }
        public string TelephoneType03 { get; set; }
        public string URL { get; set; }
    }
}
